---
- name: "Add Elasticsearch repository ({{ elasticsearch_version }})"
  yum_repository:
    name: elasticsearch
    description: "Elasticsearch repository for {{ elasticsearch_version }}.x packages"
    baseurl: "https://packages.elastic.co/elasticsearch/{{ elasticsearch_version }}/centos"
    gpgkey: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    gpgcheck: yes

- name: Install Elasticsearch.
  yum: pkg=elasticsearch state=installed
